rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :web do
    namespace :learn do
      resources :trainings do
        scope module: :trainings do
          resources :steps, only: [:show, :update]
        end
      end

      root to: "trainings#index"
    end

    namespace :auth do
      # Add a root route if you don't have one...
      # We can use users#new for now, or replace this with the controller and action you want to be the site root:
      root to: "users#new"

      # sign up page with form:
      get 'users/new' => 'users#new', as: :new_user
      post 'users' => 'users#create'

      # log in page with form:
      get '/login'     => 'sessions#new'
      post '/login'    => 'sessions#create'
      delete '/logout' => 'sessions#destroy'
    end
  end

end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
end

rails/app/models/category/question.rb
class Category::Question < ApplicationRecord
  include QuestionsRepository

  belongs_to :category
  has_many :answers
end

rails/app/models/category/question/answer.rb
class Category::Question::Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(is_correct: true) }
end

rails/app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  has_many :steps

  SIZE = 20

end

rails/app/models/training/step.rb
class Training::Step < ApplicationRecord
  belongs_to :question, class_name: "Category::Question", foreign_key: :category_question_id
  belongs_to :training
  has_many :choices, foreign_key: :training_step_id
  has_many :answers, through: :choices, class_name: "Category::Question::Answer", primary_key: :category_question_answer_id

  # scope :answered, -> { where("TRUE") }
  # scope :unanswered, -> { where("TRUE") }

  def next_step_number
    number + 1 if number != Training::SIZE
  end

  def prev_step_number
    number - 1 if number != 0
  end

  def all_answers
    question.answers
  end

  def answered?
    choices.any?
  end

  def number_of_answers_required
    question.answers_required
  end

  def text
    question.text
  end

  def has_image
    question.has_image
  end

  def options
    question.answers
  end
end

rails/app/models/training/step/choice.rb
class Training::Step::Choice < ApplicationRecord
  belongs_to :step, foreign_key: :training_step_id
  belongs_to :answer, class_name: "Category::Question::Answer", foreign_key: :category_question_answer_id
end

rails/app/models/user.rb
class User < ApplicationRecord
  has_many :trainings

  has_secure_password

	validates :email, presence: true, uniqueness: true
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/web/context_controller.rb
class Web::ContextController < ApplicationController
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if current_user.nil?
      redirect_to auth_login_path, alert: "Please log in first!"
    end
  end
end

rails/app/controllers/web/learn/context_controller.rb
class Web::Learn::ContextController < Web::ContextController
  before_action :authenticate_user!
end

rails/app/controllers/web/learn/trainings/context_controller.rb
class Web::Learn::Trainings::ContextController < Web::Learn::ContextController
  def training
    @training ||= Training.find(params[:training_id])
  end
end

rails/app/controllers/web/learn/trainings/steps_controller.rb
class Web::Learn::Trainings::StepsController < Web::Learn::Trainings::ContextController
  before_action :step

  def show

  end

  def update
    @step.update(step_params)
    @step.save!

    redirect_to learn_training_step_path(@training, @step.number)
  end

  private

  def step
    @step ||= training.steps.find_by!(number: params[:id])
  end

  def step_params
    params.require(:training_step).permit(:answer_ids, :answer_ids => [])
  end
end

rails/app/controllers/web/learn/trainings_controller.rb
class Web::Learn::TrainingsController < Web::Learn::ContextController
  def index
    @trainings = current_user.trainings
  end

  def new
    @training = Training.new(user: current_user)

    steps = Category::Question.random(Training::SIZE).each_with_index.map do |q, i|
      Training::Step.new(question: q, number: i + 1)
    end

    @training.steps = steps

    if @training.save
      flash[:alert] = "Start learning!"
      redirect_to learn_training_path(@training)
    else
      flash[:alert] = "Couldn't create new session"
      redirect_to :index
    end
  end

  def show
    @training = Training.find(params[:id])
    redirect_to learn_training_step_path(@training, @training.steps.first.number)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/web/authentication/sessions_helper.rb
module Web::Authentication::SessionsHelper
end

rails/app/helpers/web/authentication/users_helper.rb
module Web::Authentication::UsersHelper
end

rails/app/helpers/web/learn/trainings/questions/answers_helper.rb
module Web::Learn::Trainings::Questions::AnswersHelper
end

rails/app/helpers/web/learn/trainings/steps_helper.rb
module Web::Learn::Trainings::StepsHelper
end

rails/app/helpers/web/learning/trainings_helper.rb
module Web::Learning::TrainingsHelper
end

rails/app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:crossorigin => "anonymous", :integrity => "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", :src => "https://code.jquery.com/jquery-3.3.1.min.js"}

  %body
    - if current_user
      / current_user will return true if a user is logged in
      = "Logged in as #{current_user.email}"
      | #{link_to 'Home', learn_root_path} | #{link_to 'Log Out', auth_logout_path, method: :delete}
    - else
      / not logged in
      = link_to 'Home', learn_root_path
      | #{link_to 'Log In', auth_login_path} or #{link_to 'Sign Up', auth_new_user_path}
    %hr/
    - if notice
      = notice
    - if alert
      = alert
    = yield

rails/app/views/web/learn/trainings/index.html.haml
%ul
  - @trainings.each do |t|
    %li= link_to t.created_at, learn_training_path(t)

= link_to "Start new training session", new_learn_training_path

rails/app/views/web/learn/trainings/show.html.haml
%ul
  - @training.questions.each do |q|
    %li= q.text


-#link_to "Coninue training", learn_training_question_path()

rails/app/views/web/learn/trainings/steps/show.html.haml
.requirements
  -if @step.number_of_answers_required > 1
    Number of answers required:
    = @step.number_of_answers_required

  :javascript
    $(document).ready(function(){
      $("input.submit").on("click", function(){
        var n = $('.check_boxes:checked').length;

        if (n < answersRequired) {
          $('.requirements').addClass('attention')
          return false;
        }
      })
    })

%br

- if @step.has_image
  %img{src: "/questions/#{@step.question.external_identificator}.jpg"}

%br
= @step.text

= simple_form_for @step, url: learn_training_step_path(@training, @step), method: :PUT do |f|
  - suitable_display_method = @step.number_of_answers_required == 1 ? :radio_buttons : :check_boxes

  = f.input :answer_ids,
    label: false,
    as: suitable_display_method,
    collection: @step.options,
    label_method: :text,
    value_method: :id,
    include_hidden: false,
    checked: @step.answer_ids

  %div
    %button.show Show results
    = f.submit "Submit", class: :submit

%div
  - if @step.prev_step_number
    =link_to "Prev", learn_training_step_path(@training, @step.prev_step_number)

  - if @step.next_step_number
    =link_to "Next", learn_training_step_path(@training, @step.next_step_number)


%script
  == var ids = [ #{ @step.all_answers.correct.pluck(:id) * "," } ];
  == var answersRequired = #{ @step.number_of_answers_required };

:javascript
  $("button.show").on("click", function(){
    ids.forEach(function(id){
      $("label[for='training_step_answer_ids_" + id + "']").addClass('correct');
    });
    return false;
  })

:css
  .radio, .checkbox {
    display: block;
    margin: 3px;
  }

  .attention {
    color: red;
    font-weight: bold;
  }

  label {
    padding: 2px;
    margin-bottom: 3px;
  }

  label.correct {
    border: 1px solid green;
    border-radius: 3px;
  }